apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: sonarr-downloads-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti