apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ssd1/csi/sonarr
    server: {{ .Values.nas.host }}
