apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: radarr-data-pv
  resources:
    requests:
      storage: 50Gi