apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-downloads-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hdd1/multimedia/downloads
    server: {{ .Values.nas.host }}