apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
    cert-manager.io/common-name: {{ .Values.prowlarr.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: prowlarr-ingress
  namespace: prowlarr
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.prowlarr.host }}
      http:
        paths:
          - backend:
              service:
                name: prowlarr
                port:
                  number: 9696
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.prowlarr.host }}
      secretName: prowlarr-tls
