apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
    cert-manager.io/common-name: {{ .Values.qbittorrent.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: qbittorrent-ingress
  namespace: qbittorrent
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.qbittorrent.host }}
      http:
        paths:
          - backend:
              service:
                name: qbittorrent
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.qbittorrent.host }}
      secretName: qbittorrent-tls
