apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: qbittorrent
      app.kubernetes.io/name: qbittorrent
  serviceName: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
        app.kubernetes.io/instance: qbittorrent
        app.kubernetes.io/name: qbittorrent
        
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-data
            - mountPath: /downloads-incomplete
              name: qbittorrent-downloads-incomplete
            - mountPath: /downloads
              name: qbittorrent-downloads
            - mountPath: /seed
              name: qbittorrent-seed
      volumes:
        - name: qbittorrent-data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: qbittorrent-downloads-incomplete
          persistentVolumeClaim:
            claimName: downloads-incomplete-pvc
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: qbittorrent-seed
          persistentVolumeClaim:
            claimName: seed-pvc