apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  ports:
    - name: qbittorrent
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: p2p
      port: 6881
      protocol: TCP
      targetPort: 6881
    - name: p2pudp
      port: 6881
      protocol: UDP
      targetPort: 6881
  selector:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
  type: ClusterIP
