apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-downloads-incomplete-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hdd1/multimedia/incomplete-downloads
    server: {{ .Values.nas.host }}