apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  instances: 1
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-cluster-password
  certificates:
    serverTLSSecret: cnpg-server-cert
    serverCASecret: cnpg-server-cert
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: truenas-iscsi-nonroot
      resources:
        requests:
          storage: 10Gi