# cnpg cluster with democratic-csi 
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  instances: 1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteMany
      storageClassName: truenas-iscsi-nonroot
      volumeMode: Block
      resources:
        requests:
          storage: 10Gi