apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg
spec:
  instances: 1
  certificates:
    serverTLSSecret: cnpg-server-cert
    serverCASecret: cnpg-server-cert
  managed:
    roles:
    - name: app
      ensure: present
      login: true
      superuser: false
      passwordSecret:
        name: cnpg-cluster-password
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: truenas-iscsi-nonroot
      resources:
        requests:
          storage: 10Gi