apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ssd1/csi/cnpg
    server: nas.home