apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-iscsi-nonroot
  volumeMode: Block
  resources:
    requests:
      storage: 100Gi