apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-tv-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hdd1/multimedia/tv
    server: {{ .Values.nas.host }}