apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: plex-tv-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti