- name: Create Ubuntu Cloud-Init Template in Proxmox
  hosts: proxmox
  become: true
  vars_files:
    - ../vars/all.yaml
  tasks:
    - name: Download Ubuntu cloud image
      get_url:
        url: "{{ template_url }}"
        dest: "/var/lib/vz/template/{{ template_image }}"
        mode: '0644'

    - name: Resize VM
      shell: |
        qemu-img resize /var/lib/vz/template/{{ template_image }} 64G

    - name: Create a new VM
      shell: |
        qm create {{ template_id }} --name {{ template_name }} --ostype l26 \
          --memory 4096 --balloon 0 \
          --agent 1 \
          --bios ovmf --machine q35 \
          --efidisk0 {{ vm_storage }}:128K,format=raw,efitype=4m,pre-enrolled-keys=0 \
          --cpu host --cores 2 --numa 1 \
          --vga serial0 --serial0 socket \
          --net0 virtio,bridge=vmbr0

        qm importdisk {{ template_id }} /var/lib/vz/template/{{ template_image }} {{ vm_storage }}
        qm set {{ template_id }} --scsihw virtio-scsi-pci --virtio0 {{ vm_storage }}:vm-{{ template_id }}-disk-1,discard=on
        qm set {{ template_id }} --boot order=virtio0 --bootdisk virtio0
        qm set {{ template_id }} --ide2 {{ vm_storage }}:cloudinit

    - name: Copy cloud-init user config snippet to Proxmox host
      copy:
        src: ../files/cloudinit/ubuntu.yaml
        dest: /var/lib/vz/snippets/ubuntu.yaml
        mode: '0644'

    - name: Convert the VM to template
      shell: |
        qm set {{ template_id }} --cicustom "vendor=local:snippets/ubuntu.yaml"
        qm set {{ template_id }} --sshkeys ~/.ssh/authorized_keys
        qm set {{ template_id }} --ipconfig0 ip={{ vm_ip }}/24,gw={{ vm_gateway }} --nameserver {{ vm_gateway }}
        qm set {{ template_id }} --ciuser {{ ci_user }}
        
        qm template {{ template_id }}