nas:
  host: nas.home
homepage:
  host: homepage.talos.home
  services:
    radarr:
      key: ""
      host: https://radarr.talos.home
    sonarr:
      key: ""
      host: https://sonarr.talos.home
    sabnzbd:
      key: ""
      host: https://sabnzbd.talos.home
    argocd:
      key: ""
      host: https://argocd.talos.home
    prowlarr:
      key: ""
      host: https://prowlarr.talos.home
    plex:
      key: ""
      host: https://plex.talos.home