nas:
  host: nas.home
homepage:
  host: homepage.k3s.home
  services:
    radarr:
      key: ""
      host: https://radarr.k3s.home
    sonarr:
      key: ""
      host: https://sonarr.k3s.home
    sabnzbd:
      key: ""
      host: https://sabnzbd.k3s.home
    argocd:
      key: ""
      host: https://argocd.k3s.home
    prowlarr:
      key: ""
      host: https://prowlarr.k3s.home
    plex:
      key: ""
      host: https://plex.k3s.home