nas:
  host: nas.home
homepage:
  apiKeysSecretName: homepage-api-keys
  host: homepage.talos.home
  services:
    radarr:
      key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
      host: https://radarr.talos.home
    sonarr:
      key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
      host: https://sonarr.talos.home
    sabnzbd:
      key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
      host: https://sabnzbd.talos.home
    argocd:
      key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
      host: https://argocd.talos.home
    proxmox:
      enabled: true
      host: https://cad-server.home:8006/
      username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_ID}}"
      password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET}}"
      node: cad-server
    truenas:
      enabled: true
      host: https://nas.home
      version: 2
      nasType: scale
      key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
      enablePools: true
    prowlarr:
      key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
      host: https://prowlarr.talos.home
    qbittorrent:
      username: "admin"
      password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
      host: https://qbittorrent.talos.home
    seerr:
      key: "{{HOMEPAGE_VAR_SEERR_API_KEY}}"
      host: https://seerr.talos.home
    plex:
      key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
      host: https://plex.talos.home