apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multimedia
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.source.repoUrl }}
    path: {{ .Values.spec.source.multimediaPath }}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true