apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: plex
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.plex.repoUrl }}
    chart: plex-media-server
    targetRevision: {{ .Values.spec.plex.targetRevision }}
    helm:
      releaseName: plex
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
            cert-manager.io/common-name: "{{ .Values.spec.plex.host }}"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          tls:
            - secretName: plex-tls
              hosts:
                - {{ .Values.spec.plex.host }}
          ingressClassName: traefik
          url: {{ .Values.spec.plex.host }}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true