{{- if has "plex" .Values.enabledApplications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  destination:
    namespace: plex
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.source.repoUrl }}
    path: {{ .Values.spec.source.plexPath }}
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
{{- end }}