apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
    cert-manager.io/common-name: {{ .Values.overseerr.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: overseerr-ingress
  namespace: overseerr
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.overseerr.host }}
      http:
        paths:
          - backend:
              service:
                name: overseerr
                port:
                  number: 5055
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.overseerr.host }}
      secretName: overseerr-tls
