apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: home-root-ca
  secretName: home-root-ca-secret
  duration: 87600h # 10y
  renewBefore: 78840h # 9y
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: home-root-ca-issuer-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io