apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-talos-home
  namespace: envoy-gateway-system
spec:
  secretName: wildcard-talos-home
  issuerRef:
    name: home-intermediate-ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.talos.home"