ingress:
  host: keycloak.talos.home
spec:
  keycloak:
    username: ""
    clients:
      portainer:
        clientSecret: ""
      argocd:
        clientSecret: ""
      semaphore:
        clientSecret: ""