apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`)"
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: "Host(`{{ .Values.ingress.host }}`) && Header(`Content-Type`, `application/grpc`)"
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: k3s-home-tls