- import_playbook: playbooks/create-template.yaml
- import_playbook: playbooks/create-vm.yaml
- import_playbook: playbooks/wait-for-ssh.yaml
- import_playbook: playbooks/wait-for-cloud-init-finished.yaml
- import_playbook: playbooks/configure-k3s.yaml
- import_playbook: playbooks/configure-argocd.yaml
- import_playbook: playbooks/wait-for-apps.yaml
- import_playbook: playbooks/configure-portainer.yaml
- import_playbook: playbooks/finish-configuration.yaml