- name: Teardown Proxmox VMs and template
  hosts: localhost
  gather_facts: false
  become: true
  tasks:

    - name: Define VM IDs and template ID
      ansible.builtin.set_fact:
        vm_ids: [101]
        template_id: 9001

    - name: Shutdown and destroy each VM if it exists
      ansible.builtin.shell: |
        if qm status {{ item }} 2>/dev/null | grep -q running; then
          qm shutdown {{ item }} --timeout 30 || qm stop {{ item }}
        fi
        qm destroy {{ item }} --purge
      loop: "{{ vm_ids }}"
      register: destroy_vm_result
      failed_when: false
      changed_when: "'could not be found' not in destroy_vm_result.stdout"

    - name: Delete the VM template if it exists
      ansible.builtin.shell: |
        if qm status {{ template_id }} 2>/dev/null; then
          qm unlock {{ template_id }} || true
          qm destroy {{ template_id }} --purge
        fi
      register: destroy_template_result
      failed_when: false
      changed_when: "'could not be found' not in destroy_template_result.stdout"