apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-dashboard
  namespace: portainer
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
    cert-manager.io/common-name: "{{ .Values.ingress.host }}"
spec:
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portainer
                port:
                  number: 9000
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: portainer-cert-secret