apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex
  namespace: plex
spec:
  parentRefs:
    - name: homelab-gateway
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ .Values.plex.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: "180s"
        backendRequest: "170s"
      backendRefs:
        - name: plex-media-server
          port: 32400
          group: ""
          kind: Service
          weight: 1
