apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
    cert-manager.io/common-name: {{ .Values.plex.host }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: plex-media-server-ingress
  namespace: plex
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.plex.host }}
      http:
        paths:
          - backend:
              service:
                name: plex-media-server
                port:
                  number: 32400
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.plex.host }}
      secretName: plex-tls
