apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-media-server
  namespace: plex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex-media-server
  serviceName: plex-media-server
  template:
    metadata:
      labels:
        app: plex-media-server
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex-media-server
        
    spec:
      initContainers:
        - name: format-and-mount
          image: ubuntu
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update && apt install -y e2fsprogs mount && \
              if ! blkid /dev/plex-data; then \
                echo "Formatting /dev/plex-data"; \
                mkfs.ext4 /dev/plex-data; \
              fi && \
              mkdir -p /mnt/config && \
              mount /dev/plex-data /mnt/config && \
              chown -R 1000:1000 /mnt/config && \
              cp -a /mnt/config/. /emptydir/ && \
              umount /mnt/config
          volumeDevices:
            - name: plex-device
              devicePath: /dev/plex-data
          volumeMounts:
            - name: plex-filesystem
              mountPath: /emptydir

      containers:
        - env:
            - name: ADVERTISE_IP
              value: https://{{ .Values.plex.host }}:443
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          image: index.docker.io/plexinc/pms-docker:1.41.6.9685-d301f511a
          imagePullPolicy: IfNotPresent
          name: plex-media-server-pms
          ports:
            - containerPort: 32400
              name: pms
          volumeMounts:
            - name: plex-filesystem
              mountPath: /config
            - mountPath: /transcode
              name: pms-transcode
            - mountPath: /data/tv
              name: plex-tv
              readOnly: true
            - mountPath: /data/movies
              name: plex-movies
              readOnly: true
      serviceAccountName: plex-media-server
      terminationGracePeriodSeconds: 120
      volumes:
        - name: plex-device
          persistentVolumeClaim:
            claimName: config-pvc
        - name: plex-filesystem
          emptyDir: {}

        - name: pms-transcode
          emptyDir: {}
        - name: plex-tv
          persistentVolumeClaim:
            claimName: tv-pvc
        - name: plex-movies
          persistentVolumeClaim:
            claimName: movies-pvc
