apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-movies
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: pv-movies
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti