apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.argoCd.repoUrl }}
    chart: argo-cd
    targetRevision: {{ .Values.spec.argoCd.targetRevision }}
    helm:
      releaseName: argo
      values: |              
        configs:
          cm:
            oidc.tls.insecure.skip.verify: "true"
            url: {{ .Values.spec.argoCd.url }}
            kustomize.buildOptions: "--enable-helm"
            oidc.config: |
              name: Keycloak
              issuer: {{ .Values.spec.argoCd.oidc.issuer }}
              clientID: {{ .Values.spec.argoCd.oidc.clientID }}
              clientSecret: {{ .Values.spec.keycloak.clients.argocd.clientSecret }}
          params:
            server.insecure: "true"
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.argocdPath }}
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true 
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true