apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.argoCd.repoUrl }}
    chart: argo-cd
    targetRevision: {{ .Values.spec.argoCd.targetRevision }}
    helm:
      releaseName: argo
      values: |              
        configs:
          secret:
            createSecret: true
            extra:
              oidc.keycloak.clientSecret: {{ .Values.spec.keycloak.clients.argocd.clientSecret }}
          cm: 
            url: {{ .Values.spec.argoCd.url }}
            oidc.config: |
              name: Keycloak
              issuer: {{ .Values.spec.argoCd.oidc.issuer }}
              clientID: {{ .Values.spec.argoCd.oidc.clientID }}
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: ["openid", "profile", "email", "groups"]
              {{- if .Values.spec.argoCd.caCert }}
              rootCA: |
                {{ .Values.spec.argoCd.caCert | indent 8 }}
              {{- end }}
            kustomize.buildOptions: "--enable-helm"
          params:
            server.insecure: "true"
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.argocdPath }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false