apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: {{ .Values.spec.certManager.repoUrl }}
    targetRevision: {{ .Values.spec.certManager.targetRevision }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true