apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.certManager.repoUrl }}
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    targetRevision: {{ .Values.spec.certManager.targetRevision }}
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.portainerPath }}
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true