apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: cnpg-system
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.cnpg.repoUrl }}
    chart: cloudnative-pg
    targetRevision: {{ .Values.spec.cnpg.targetRevision }}
    helm:
      releaseName: cnpg
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true