apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.democraticcsi.repoUrl }}
    chart: democratic-csi
    targetRevision: {{ .Values.spec.democraticcsi.targetRevision }}
    helm:
      releaseName: democratic-csi
      values: |              
        csiDriver:
          name: "org.democratic-csi.nfs"
        storageClasses:
        - name: truenas-nfs-nonroot
          defaultClass: false
          reclaimPolicy: Retain
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
          parameters:
            fsType: nfs
          mountOptions:
          - noatime
          - nfsvers=4
        driver:
          existingConfigSecret: democratic-csi-nfs-secret
          config:
            driver: freenas-nfs            