apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.democraticcsi.repoUrl }}
    chart: democratic-csi
    targetRevision: {{ .Values.spec.democraticcsi.targetRevision }}
    helm:
      releaseName: democratic-csi
      values: |              
        csiDriver:
          name: "org.democratic-csi.iscsi"
        storageClasses:
        - name: truenas-iscsi-nonroot
          defaultClass: false
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
          parameters:
            fsType: ext4
        driver:
          config:
            driver: freenas-iscsi
            existingConfigSecret: democratic-csi-secret