apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  sources:
    - repoURL: {{ .Values.spec.envoyGateway.repoUrl }}
      chart: gateway-helm
      targetRevision: {{ .Values.spec.envoyGateway.targetRevision }}
      helm:
        releaseName: envoy-gateway
        skipCRDs: true
        values: |
          envoyGateway:
            provider:
              type: Kubernetes
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: {{ .Values.spec.source.envoyGatewayPath }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true