apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    namespace: keycloak-operator
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.keycloakPath }}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background 
      - ServerSideApply=true
      - RespectIgnoreDifferences=true