apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    namespace: keycloak-operator
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.keycloakPath }}
    targetRevision: HEAD
    helm:
      values: |
        spec:
          keycloak:
            username: {{ .Values.spec.keycloak.username }}
            clients:
              argocd:
                clientSecret: {{ .Values.spec.keycloak.clients.argocd.clientSecret }}
  - repoURL: {{ .Values.spec.keycloak.repoUrl }}
    targetRevision: {{ .Values.spec.keycloak.targetRevision }}
    path: kubernetes
    directory:
      recurse: false
      include: '{keycloaks.k8s.keycloak.org-v1.yml,keycloakrealmimports.k8s.keycloak.org-v1.yml,kubernetes.yml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
