apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: portainer
    server: {{ .Values.spec.destination.server }}
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: {{ .Values.spec.source.portainerPatchPath }}
    kustomize:
      enabled: true
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.portainerPath }}
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false 