apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: semaphore
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.semaphore.repoUrl }}
    chart: semaphore
    targetRevision: {{ .Values.spec.semaphore.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
            cert-manager.io/common-name: "{{ .Values.spec.semaphore.host }}"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - host: "{{ .Values.spec.semaphore.host }}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - "{{ .Values.spec.semaphore.host }}"
              secretName: semaphore-cert-tls

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true