apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd     
spec:
  project: default
  destination:
    namespace: semaphore
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.semaphore.repoUrl }}
    chart: semaphore
    targetRevision: {{ .Values.spec.semaphore.targetRevision }}
    helm:
      values: |
        admin:
          create: false
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: home-intermediate-ca-issuer
            cert-manager.io/common-name: "{{ .Values.spec.semaphore.host }}"
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - host: "{{ .Values.spec.semaphore.host }}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
              - "{{ .Values.spec.semaphore.host }}"
              secretName: semaphore-cert-tls
        oidc:
          enable: true
          providers:
            keycloak:
              display_name: Keycloak
              provider_url: {{ .Values.spec.semaphore.oidc.issuer }}
              redirect_url: https://{{ .Values.spec.semaphore.host }}/api/auth/oidc/keycloak/redirect
              client_id: semaphore
              client_secret: {{ .Values.spec.keycloak.clients.semaphore.clientSecret | quote }}
              username_claim: preferred_username
              name_claim: preferred_username
              email_claim: email
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false 
    syncOptions:
      - CreateNamespace=true