apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: portainer
    repo: https://portainer.github.io/k8s/
    version: "2.14.0"    # example version
    releaseName: portainer
    namespace: portainer
    valuesFile: values.yaml