spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoUrl: https://github.com/dokkeberg/homelab
    targetRevision: HEAD
    multimediaPath: servarr/applications/multimedia
    plexPath: servarr/applications/plex
    plexVolumesPath: servarr/applications/plex-volumes
    sonarrPath: servarr/applications/sonarr
    sonarrVolumesPath: servarr/applications/sonarr-volumes
    radarrPath: servarr/applications/radarr
    radarrVolumesPath: servarr/applications/radarr-volumes
    sabnzbdPath: servarr/applications/sabnzbd
    sabnzbdVolumesPath: servarr/applications/sabnzbd-volumes
    prowlarrPath: servarr/applications/prowlarr
    prowlarrVolumesPath: servarr/applications/prowlarr-volumes
    homepagePath: servarr/applications/homepage
  plex:
    repoUrl: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    targetRevision: 1.0.2
    host: plex.k3s.home