enabledApplications:
  - plex
  - plex-volumes
  - prowlarr
  - prowlarr-volumes
  - qbittorrent
  - qbittorrent-volumes
  - radarr
  - radarr-volumes
  - recyclarr
  - sabnzbd
  - sabnzbd-volumes
  - seerr
  - seerr-volumes
  - sonarr
  - sonarr-volumes
