apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            icon: argocd.png
            href: {{ .Values.homepage.services.argocd.host }}
            description: GitOps CI/CD
            namespace: argocd
            app: argocd
            widget:
              type: argocd
              url: {{ .Values.homepage.services.argocd.host }}
              key: {{ .Values.homepage.services.argocd.key }}
    - Media:
        - Radarr:
            icon: radarr.png
            href: {{ .Values.homepage.services.radarr.host }}
            description: Movies tracker
            namespace: radarr
            app: radarr
            widget:
              type: radarr
              url: {{ .Values.homepage.services.radarr.host }}
              key: {{ .Values.homepage.services.radarr.key }}
        - Sonarr:
            icon: sonarr.png
            href: {{ .Values.homepage.services.sonarr.host }}
            description: TV tracker
            namespace: sonarr
            app: sonarr
            widget:
              type: sonarr
              url: {{ .Values.homepage.services.sonarr.host }}
              key: {{ .Values.homepage.services.sonarr.key }}
        - SABnzbd:
            icon: sabnzbd.png
            href: {{ .Values.homepage.services.sabnzbd.host }}
            description: Usenet downloader
            namespace: sabnzbd
            app: sabnzbd
            widget:
              type: sabnzbd
              url: {{ .Values.homepage.services.sabnzbd.host }}
              key: {{ .Values.homepage.services.sabnzbd.key }}
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""