apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
  serviceName: radarr
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/instance: radarr
        app.kubernetes.io/name: radarr
        
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          volumeMounts:
            - mountPath: /config
              name: radarr-config
            - mountPath: /movies
              name: radarr-movies
            - mountPath: /downloads
              name: radarr-downloads
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: data-pvc
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: movies-pvc
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: downloads-pvc