apiVersion: v1
kind: PersistentVolume
metadata:
  name: seerr-data-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ssd1/csi/seerr
    server: {{ .Values.nas.host }}
