apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: sonarr
spec:
  ports:
    - name: sonarr
      port: 8989
      protocol: TCP
      targetPort: 8989
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
  type: ClusterIP
