apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: sonarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
  serviceName: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr
        
    spec:
      initContainers:
        - name: format-data
          image: ubuntu
          securityContext:
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update && apt install -y e2fsprogs && \
              if ! blkid /dev/sonarr-data; then \
                echo "Formatting /dev/sonarr-data"; \
                mkfs.ext4 /dev/sonarr-data; \
              else \
                echo "/dev/sonarr-data already formatted"; \
              fi
          volumeDevices:
            - name: sonarr-device
              devicePath: /dev/sonarr-data

      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          securityContext:
            privileged: true    # or at least allow mount capability
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          volumeDevices:
            - name: sonarr-device
              devicePath: /dev/sonarr-data
          volumeMounts:
            - mountPath: /tv
              name: sonarr-tv
            - mountPath: /downloads
              name: sonarr-downloads
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /config && \
              mount /dev/sonarr-data /config && \
              chown -R 1000:1000 /config && \
              exec /init
      volumes:
        - name: sonarr-device
          persistentVolumeClaim:
            claimName: data-pvc
        - name: sonarr-tv
          persistentVolumeClaim:
            claimName: tv-pvc
        - name: sonarr-downloads
          persistentVolumeClaim:
            claimName: downloads-pvc