- name: Wait for SSH
  hosts: localhost
  tasks:
    - name: Wait for SSH
      wait_for:
        port: 22
        host: "{{ VMIP }}"
        timeout: 300

    - name: Add host to inventory
      add_host:
        name: newvm
        ansible_host: "{{ VMIP }}"
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
