- name: Configure Kubernetes
  hosts: newvm
  become: true
  tasks:
    - name: Install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Install Helm via snap
      ansible.builtin.command: snap install helm --classic

    - name: Get CoreDNS config
      ansible.builtin.command: kubectl -n kube-system get configmap coredns -o json
      register: coredns_config

    - name: Define CoreDNS patch block
      ansible.builtin.set_fact:
        coredns_patch_block: |
          k3s.home:53 {
            forward . 192.168.1.1
            cache 30
            log
          }

    - name: Patch CoreDNS
      ansible.builtin.shell: |
        echo '{{ coredns_config.stdout }}' | \
        jq --arg block "\n{{ coredns_patch_block | replace('\n', '\\n') }}" '.data.Corefile += $block' | \
        kubectl apply -f -
      args:
        executable: /bin/bash

    - name: Restart CoreDNS pods
      ansible.builtin.command: kubectl -n kube-system delete pod -l k8s-app=kube-dns