- name: Configure ArgoCD
  hosts: newvm
  collections:
  - kubernetes.core
  become: true
  tasks:
  - name: Add ArgoCD Helm repo
    ansible.builtin.command: helm repo add argo https://argoproj.github.io/argo-helm

  - name: Update Helm repos
    ansible.builtin.command: helm repo update

  - name: Install ArgoCD
    kubernetes.core.helm:
      name: argocd
      chart_ref: argo/argo-cd
      namespace: argocd
      create_namespace: true
      values:
        server:
          extraArgs:
            - --insecure
    environment:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  - name: Wait for ArgoCD to become available
    ansible.builtin.command: >
      kubectl wait -n argocd deployment/argocd-server --for=condition=available --timeout=90s
  
  - name: Check if ArgoCD CLI is installed
    ansible.builtin.stat:
      path: /usr/local/bin/argocd
    register: argocd_bin

  - name: Download and install ArgoCD CLI via curl if missing
    ansible.builtin.shell: |
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      chmod 0555 /usr/local/bin/argocd
    args:
      creates: /usr/local/bin/argocd
    become: true
    when: not argocd_bin.stat.exists

  - name: Genrate random ARGOCD_OIDC_SECRET 
    ansible.builtin.set_fact:
      argocd_oidc_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"

  - name: Generate random PORTAINER_SECRET
    ansible.builtin.set_fact:
      portainer_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"

  - name: Generate random SEMAPHORE_SECRET
    ansible.builtin.set_fact:
      semaphore_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"

  - name: Login to ArgoCD
    ansible.builtin.shell: |
      argocd login --core
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true

  - name: Set kubectl context namespace to argocd
    ansible.builtin.shell: |
      kubectl config set-context --current --namespace=argocd
    environment:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true

  - name: Check if ArgoCD app 'infrastructure' exists
    ansible.builtin.shell: |
      argocd app get infrastructure
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true
    register: app_check
    failed_when: false
    changed_when: false

  - name: Create ArgoCD app 'infrastructure' if missing
    ansible.builtin.shell: |
      argocd app create infrastructure \
        --repo https://github.com/dokkeberg/homelab \
        --path infrastructure/applications/app-of-apps \
        --dest-server https://kubernetes.default.svc \
        --dest-namespace argocd \
        --parameter "spec.keycloak.clients.portainer.clientSecret={{ portainer_secret }}" \
        --parameter "spec.keycloak.clients.semaphore.clientSecret={{ semaphore_secret }}" \
        --parameter "spec.keycloak.clients.argocd.clientSecret={{ argocd_oidc_secret }}"
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true
    when: app_check.rc != 0

  - name: Sync ArgoCD app 'infrastructure'
    ansible.builtin.shell: |
      argocd app sync infrastructure
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true

  - name: Refresh ArgoCD app 'argocd/argocd'
    ansible.builtin.shell: |
      argocd app get argocd --hard-refresh --insecure --plaintext
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true

  - name: Sync ArgoCD app 'argocd/argocd'
    ansible.builtin.shell: |
      argocd app sync argocd --insecure --plaintext
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true
    register: sync_result
    retries: 5
    delay: 10
    until: sync_result.rc == 0

  - name: Refresh ArgoCD app 'portainer'
    ansible.builtin.shell: |
      argocd app get portainer --hard-refresh
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true

  - name: Sync ArgoCD app 'portainer'
    ansible.builtin.shell: |
      argocd app sync portainer
    environment:
      HOME: /root
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    become: true