- name: Configure democratic-csi
  hosts: newvm
  become: true
  vars_files:
  - ../vars/all.yaml
  tasks:
    - name: Read private SSH key
      ansible.builtin.slurp:
        src: "{{ lookup('env', 'HOME') }}/ansible-secrets/democrat-ssh"
      register: private_key
      delegate_to: localhost

    - name: Read api key
      ansible.builtin.slurp:
        src: "{{ lookup('env', 'HOME') }}/ansible-secrets/democrat-apikey"
      register: api_key
      delegate_to: localhost

    - name: Decode private key
      set_fact:
        private_key_content: "{{ private_key['content'] | b64decode }}"

    - name: Decode api key
      set_fact:
        nas_apikey: "{{ api_key['content'] | b64decode }}"

    - name: Render democratic-csi secret manifest to a file
      ansible.builtin.template:
        src: ../files/democratic-csi/democratic-csi-secret.yaml.j2
        dest: /tmp/democratic-csi-secret.yaml
      vars:
        # Pass any variables needed by your template here, e.g.
        namespace: default
        private_key_content: "{{ hostvars['proxmox']['private_key_for_newvm'] }}"

    - name: Apply the democratic-csi secret manifest using kubectl
      ansible.builtin.shell: | 
        kubectl apply -f /tmp/democratic-csi-secret.yaml
      args:
        executable: /bin/bash