apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/hdd1/multimedia/movies
    server: {{ .Values.nas.host }}
  storageClassName: nfs-multimedia-movies