apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  namespace: sabnzbd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sabnzbd
      app.kubernetes.io/name: sabnzbd
  serviceName: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
        app.kubernetes.io/instance: sabnzbd
        app.kubernetes.io/name: sabnzbd
        
    spec:
      containers:
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
          volumeMounts:
            - mountPath: /config
              name: sabnzbd-config
            - mountPath: /downloads-incomplete
              name: sabnzbd-downloads-incomplete
            - mountPath: /downloads
              name: sabnzbd-downloads
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: data-pvc
        - name: sabnzbd-downloads-incomplete
          persistentVolumeClaim:
            claimName: downloads-incomplete-pvc
        - name: sabnzbd-downloads
          persistentVolumeClaim:
            claimName: downloads-pvc