apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-data-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/ssd1/csi/prowlarr
    server: {{ .Values.nas.host }}
