spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/dokkeberg/homelab
    targetRevision: HEAD
    argocdPath: infrastructure/applications/argocd
    certManagerPath: infrastructure/applications/cert-manager
    cnpgPath: infrastructure/applications/cnpg
    keycloakPath: infrastructure/applications/keycloak-operator
    corednsPath: infrastructure/applications/coredns
    envoyGatewayPath: infrastructure/applications/envoy-gateway
  argoCd:
    repoUrl: https://argoproj.github.io/argo-helm
    url: https://argocd.talos.home
    oidc:
      issuer: https://keycloak.talos.home/realms/home
      clientID: argocd
    targetRevision: 9.5.21
    caCert: ""
  cnpg:
    repoUrl: https://cloudnative-pg.github.io/charts
    targetRevision: 0.28.3
  certManager:
    repoUrl: https://charts.jetstack.io
    targetRevision: 1.20.2
  keycloak:
    repoUrl: https://github.com/keycloak/keycloak-k8s-resources.git
    targetRevision: 26.6.3
    host: keycloak.talos.home
    username: cad
    clients:
      argocd:
        clientSecret: "foo"
  democraticcsi:
    repoUrl: https://democratic-csi.github.io/charts/
    targetRevision: 0.15.1
    username: ""
    apiKey: ""
    host: nas.home
  envoyGateway:
    repoUrl: https://github.com/envoyproxy/gateway
    targetRevision: 1.8.1
